### ISSUE TITLE
control multiple fan support

### ISSUE THREAD

**Issue by thomasesr** [KlausMu/esp32-fan-controller#1]
Hello. It would be nice to have support for multiple fans since the ESP32 Hardware is capable enough.

**Comment by KlausMu** [comment]
How would you like to control multiple fans?
- "temperature controller mode" or "pwm mode"?
- all with the same target temperature, or different target temperatures?
- using only one temperature sensor for all fans, or each fan with its own temperature sensor?

Note that it should be possible to simply connect the pwm signal to more than one fan to let them run all at the same speed.

There are so many combinations I can think of, I don't know if this can easily be achieved in a generic way. Maybe it would be better simply to use my project as a starting point and to adapt it to your needs?

**Comment by lrascao** [comment]
that's actually what i did, i'm controlling 8 PWM fans using mqtt in my project. Your project helped a lot! Thanks!

**Comment by thomasesr** [comment]
> How would you like to control multiple fans?
> 
>     * "temperature controller mode" or "pwm mode"?
> 
>     * all with the same target temperature, or different target temperatures?
> 
>     * using only one temperature sensor for all fans, or each fan with its own temperature sensor?
> 
> 
> Note that it should be possible to simply connect the pwm signal to more than one fan to let them run all at the same speed.
> 
> There are so many combinations I can think of, I don't know if this can easily be achieved in a generic way. Maybe it would be better simply to use my project as a starting point and to adapt it to your needs?

My thinking was having multiple pwm signals and multiple tacho inputs and maybe just a simple 4 point temperature curve you can configure for each (hardcoded even). Similarly of what you can find in BIOS fan control of motherboards (not the really expensive ones).

**Comment by KlausMu** [comment]
Sure, this could be done

- see "temperatureControll.cpp" for creating a 4 point temperature curve

- almost all the other files have to be adjusted so that not only one fan/temperature sensor is recognized, but many. But this should be quite easy to do. At least for the sensors and fan control itself. Bringing all these information to the display is maybe the hardest part, because there is not so many space left :-)

If you have any questions, feel free to ask.
