### ISSUE TITLE
No level shifter?

### ISSUE THREAD

**Issue by vekexasia** [KlausMu/esp32-fan-controller#10]
I see there is no level shifter from 3.3 to 5v for the PWM line. I thought pwm needed to run 5v minimum?

**Comment by KlausMu** [comment]
I used three different fans, level shifter was not needed.
Please see [Wiki](https://github.com/KlausMu/esp32-fan-controller/wiki/02-Obstacle-ESP32-electronics), "5V for fan pwm and tacho vs. 3.3V for ESP32" at the bottom.
