### ISSUE TITLE
esp8266 setup

### ISSUE THREAD

**Issue by kelmes1** [KlausMu/esp32-fan-controller#12]
I'm trying to get the d1 mini to work with this, since the guide mentioned it could be done with minor modifications. I'm only getting a lot of compilation errors and I haven't got much succes with it.

**Comment by KlausMu** [comment]
Well, yes, I think you are right. At the time of writing the guide, the code was not as ESP32 specific as it is now.
I suggest you give the ESP32 a try.

**Comment by kelmes1** [comment]
Thanks for your response, I'll give that a try instead.

**Comment by kelmes1** [comment]
Thanks for your response, I'll give it a try instead.
