### ISSUE TITLE
DS18B20 Temperature probe

### ISSUE THREAD

**Issue by thomasesr** [KlausMu/esp32-fan-controller#2]
It would be nice to also have the DS18B20 (1-wire) temperature sensor since you can have multiple sensors in the same IO pin you would be able to have a temperature sensor for each Fan and an ambient temperature sensor.

**Comment by KlausMu** [comment]
There are so many temperature sensors out there, it is impossible to support all of them.
It should be very easy to adapt the code to support other sensors than the BME280 used by me.
Just have a look at "sensorBME280.h" and "sensorBME280.cpp".

**Comment by lrascao** [comment]
biggest advantage of DS18B20 is that it uses the 1-wire protocol, with 1 GPIO you can read from several of these

**Comment by KlausMu** [comment]
Ok, I see. The BME280 sensors uses I2C, so with only 2 GPIOs you can also have up to 127 sensors.

**Comment by thomasesr** [comment]
DS18B20 its way cheaper, specially for a simple fan control and you only need to monitor temperature and not pressure and humidity. Also it has a wider range of temperature to measure. Which is nice.

**Comment by tricoos** [comment]
The main advantage for me is that the DS18B20 is available with a longer cable and waterproof so you can position it way easier than the non-waterproof BME board.
