### ISSUE TITLE
support for 2 fans

### ISSUE THREAD

**Issue by belangerpascal** [KlausMu/esp32-fan-controller#22]
I'm looking at using your code to control fans inside a rack mount enclosure and would it be possible to control 2 fans?

Thanks

**Comment by KlausMu** [comment]
2 fans with the same pwm signal? Should work, simply try to connect the PWM pin to both fans.
Tacho pin should be connected to only one single fan.
Makes only sense if you have two identical fans ...

If you want to control 2 fans independantly from each other, with different pwm values, software needed to changed.
