### ISSUE TITLE
LCD Display 20x4

### ISSUE THREAD

**Issue by givuzeta** [KlausMu/esp32-fan-controller#23]
Hi Klaus,
Thank you so much for this great project, it works perfectly! For the moment it's on the breadboard but I will make the circuit soon.
I have a spare 20x4 LCD display that can be driven by I2C, I would like to use it to print the temp, humidity and fan speed values.
I tried to look into it but it's above my coding capability, do you have any suggestion or anything in your to-do list?
Thank you in advance for your help and keep up the good work!

Cheers,
G

**Comment by KlausMu** [comment]
Glad the hear the project is helpful for you!

There are so many different displays out there, I think it is impossible to try to support all of them.
I'm afraid that not every 20x4 LCD will work the same way, so without knowing which device exactly you are trying to use, it is hard to say how to do it.

My advice is that you try to do a very simple example only to get the display running. Once you know how to do it and which library is needed for driving the LCD, you can think about how to bring the fan controller code and the LCD example together.

I once used a 20x4 LCD in a different project, and this library worked for me:
https://github.com/johnrickman/LiquidCrystal_I2C
In PlatformIO, search for "LiquidCrystal I2C"

**Comment by givuzeta** [comment]
Ok, that's a good point to start from, I'll try to figure it out.
Thank you, Klaus!!
