### ISSUE TITLE
How to connect three fans

### ISSUE THREAD

**Issue by nrizzano** [KlausMu/esp32-fan-controller#24]
Hi,
Is it possible to connect three fans to this scheme?
The three fans must be controlled all together (for example, if I set the speed to 50% with PWM, all three will go to 50%), if the temperature exceeds a certain threshold, the three fans must start and must adapt the speed based on the thresholds that I set.

I am able to make changes to the software, but for the electrical scheme I need help.

Thanks

**Comment by KlausMu** [comment]
If all three fans are identical, you can simply connect all three fans to the same GND, 12V/5V and pwm signal. But connect only one fan to the tacho signal input. No change in the software is needed.

**Comment by nrizzano** [comment]
Thank you
