### ISSUE TITLE
Multiple fan support?

### ISSUE THREAD

**Issue by imp1sh** [KlausMu/esp32-fan-controller#25]
Hi,

I'm thinking about using this for a PV inverter that has no active cooling but gets pretty hot. For that I'd like to control 4 fans that should spin up when the temperature sensor gets high values. That sensor I'd like to attach to the heatsink of the inverter.
Does this sound doable to you with your project?

Thank you

**Comment by KlausMu** [comment]
Yes, I think it is usable.
Did you have a look in the closed issues? This seems to be similar to your case: https://github.com/KlausMu/esp32-fan-controller/issues/24
