### ISSUE TITLE
Home Assistant - Fan Controller after some time 'not availible'

### ISSUE THREAD

**Issue by richie241** [KlausMu/esp32-fan-controller#27]
I have the following problem:
After a few hours, the 'Fan Controller' control is no longer available in HA. The fan sensors continue to run and work.
HA + MQTT latest version, hosted on a Synology 923+

![fan control ha](https://github.com/user-attachments/assets/18adaf61-dc59-44bf-9b2f-aa3ec6648b00)

**Comment by KlausMu** [comment]
Could you run an additional MQTT client (e.g. MQTT Explorer), keep it running and watch what is going on?

The topic of interest is "esp32_fan_controller/stat/STATUS"
Payload "online" is sent when the fan controller powers up.
Payload "offline" is sent when the fan controller disconnects from the mqtt broker.
In MQTT explorer, in the history you see when which payload was sent.
![image](https://github.com/user-attachments/assets/be45bb1f-ac32-41b5-a45d-96faacb36ef9)

![image](https://github.com/user-attachments/assets/95b1b98b-8621-40ff-a12a-d79d38f070ff)

Maybe the connection between the fan controller and the MQTT broker was lost, and after reconnection "online" was not sent again. You could check in the history of the sensors if you had continous updates or if you see a gap there (which could mean the connection was lost at some point).

**Comment by KlausMu** [comment]
I am pretty sure that the connection to the mqtt broker was lost at some point, and was recovered later. This would explain why sensors got updated again, but not the online status.

I just updated the source with a simple bugfix, to send the online status again after a reconnect.
https://github.com/KlausMu/esp32-fan-controller/commit/e20e0c3fef71c5be7a94b174af962c7f064f544c

Could you please check an try this version?

**Comment by richie241** [comment]
Thanks, i had a look with MQTT Explorer:

fline
21.09.2024 16:56:38 
offline
21.09.2024 16:55:59(-38.43 seconds) 
offline
21.09.2024 16:54:47(-72.19 seconds) 
offline
21.09.2024 16:45:21(-9.44 minutes) 
offline
21.09.2024 16:15:56(-29.42 minutes) 
offline
21.09.2024 15:06:20(-69.6 minutes) 
online


I test the new Version now and give you feedback :-)

**Comment by KlausMu** [comment]
Hi @richie241 , any update for us?
Do you still get "not available"? Or do the reconnects work?

**Comment by richie241** [comment]
Sorry for the late reply. We were on vacation. The change went through without any errors during that time, everything seems to be working. Thank you very much.
