### ISSUE TITLE
Fan never stops

### ISSUE THREAD

**Issue by srg74** [KlausMu/esp32-fan-controller#7]
Here is a problem, when temperature falling below target point fan never stops.

**Comment by KlausMu** [comment]
The reason for this can be seen in file "temperatureController.cpp":

`} else if (difftemp <= 0.0) {
// Temperature is below target temperature. Run fan at minimum speed.
newPWMvalue = pwmMinimumValue;`

pwmMinimumValue can be set in file "config.h". Default is:

`const int pwmMinimumValue            = 120;`

**Comment by srg74** [comment]
Yes, I figured. Sorry for useless post and thank you for excellent code! Your code made to another great project https://github.com/Aircoookie/WLED
